---
kind: pipeline
type: docker
name: analytics-ts-npm-pipeline

platform:
  arch: amd64
  os: linux

trigger:
  event:
    exclude:
    - tag

steps:
  - name: install
    image: node:18
    commands:
      - npm i

  - name: test
    image: node:18
    commands:
      - npm run test:coverage
    depends_on: [ install ]

  - name: release
    image: node:18
    group: release
    commands:
      - git fetch --tags
      - npm run pre-release
      - npm run release
      - last_tag=$(git describe --abbrev=0 --tags)
      - git tag -d $last_tag
      - git commit --amend -m "$(git show -s --format=%s) [skip ci]"
      - git tag -a $last_tag -m "$(git show -s --format=%s)"
    when:
      branch: main
    depends_on: [test]

  - name: push
    image: appleboy/drone-git-push:0.2.1
    settings:
      remote_name: origin
      branch: main
      force: false
      author_name: drone
      author_email: drone@s3y.io
      followtags: true
    environment:
      DRONE_NETRC_USERNAME:
        from_secret: vault_dev_netrc_username
      DRONE_NETRC_PASSWORD:
        from_secret: vault_dev_netrc_password
      DRONE_NETRC_MACHINE:
        from_secret: vault_dev_netrc_machine
    when:
      branch: main
    depends_on: [release]

  - name: publish
    image: plugins/npm:1.0.0
    settings:
      username:
        from_secret: vault_npmjs_username
      password:
        from_secret: vault_npmjs_password
      token:
        from_secret: vault_npmjs_token
      registry: https://registry.npmjs.org
      access: public
    when:
      branch: main
    depends_on: [push]
---
kind: secret
name: vault_npmjs_username
get:
  path: secret/data/dev/npmjs
  name: username
---
kind: secret
name: vault_npmjs_password
get:
  path: secret/data/dev/npmjs
  name: password
---
kind: secret
name: vault_npmjs_token
get:
  path: secret/data/dev/npmjs
  name: token
---
kind: secret
name: vault_dev_netrc_username
get:
  path: secret/data/dev/git
  name: username
---
kind: secret
name: vault_dev_netrc_password
get:
  path: secret/data/dev/git
  name: password
---
kind: secret
name: vault_dev_netrc_machine
get:
  path: secret/data/dev/git
  name: machine
